### ISSUE TITLE
Remove API keys and replace them with environment variables

### ISSUE THREAD

**Issue by angelyurii** [DurgaShree24/Firestore-sveltekit#1]
I was exploring my searches on how to use Firestore with SvelteKit and came across this. There's a fatal flaw in `/src/firebase.js`...

### :warning: You leaked your API keys for Firebase!

People who can access your keys can do anything with your project. It's a good idea to replace the code and make some changes to prevent this from happening again.

The best way to attack this is to install `dotenv` into this project with *npm*, and in `/src/firebase.js`, add this in at the top of the file:

```ts
import dotenv from 'dotenv';
dotenv.config();
const {
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGE_SENDER_ID,
    FIREBASE_APP_ID,
} = process.env;

// ...rest of your code below...
```

Then, in the `firebaseConfig` constant, replace all your strings with the environment variables mentioned in the code block above. For example, change `apiKey: "[KEYHERE]"` to `apiKey: FIREBASE_API_KEY`. So on, so forth.

After that, create a file called `.env` at the **root** of your project. Propagate it with standard `KEY=VALUE` lines, similar to this (replace `[value]` with the key/domain/id/etc.):

```env
FIREBASE_API_KEY=[value]
FIREBASE_AUTH_DOMAIN=[value]
FIREBASE_PROJECT_ID=[value]
FIREBASE_STORAGE_BUCKET=[value]
FIREBASE_MESSAGE_SENDER_ID=[value]
FIREBASE_APP_ID=[value]
```

Before you push your changes, **regenerate your keys** and test everything. Save yourself the hassle of spamming extra commits.

If you have any questions on this issue, don't be afraid to ask. If this issue is fixed, add something along the lines of `Fix #1` in your commit message. Happy coding!

**Comment by DurgaShree24** [comment]
Thanks!!
